### ISSUE TITLE
Usage and new cleaner bug

### ISSUE THREAD

**Issue by rhetenor** [monoclecat/cleaning-schedule-generator#11]
Hello,
just tried to get your code working. Since there is no README I'm a bit insecure if I'm doing it right.
I'm using Python 3.8.1 and django 3.0.4. 
I've deleted the existing `db.sqlite` (btw I would recommend to put this in gitignore since there are existing users in it with email addresses and hashes) and recreated it with `python3 manage.py migrate`. Afterwards I started the server with `python3 manage.py runserver` . At first I've got a template error in https://github.com/monoclecat/cleaning-schedule-generator/blob/e8928fdf93376b4cbc8495486ddff8210b6bf5d0/webinterface/templates/webinterface/base.html#L2
saying staticfiles is not known. Changing it to `{% load static %}` resolved the issue and the app was working.

Now the problem is whenever I try to create a new cleaner it says: 
`KeyError at /putzer/neu/`
`'schedule_group'`

The cleaner gets created but it is marked as moved out and cannot be assigned to tasks. Maybe you've got a solution since the program as such looks very good and I would be happy to use it. 
Furthermore thanks for sharing your work!

Traceback:
[traceback_key_error.txt](https://github.com/monoclecat/cleaning-schedule-generator/files/4302222/traceback_key_error.txt)

**Comment by monoclecat** [comment]
Thanks for the heads up on the database! I deleted it right away. 
I just left this project hanging as I realized I really need to start doing stuff for uni. 
In two weeks I'll be finished with my exams and will tidy up this project and give it a README.

**Comment by rhetenor** [comment]
Just to let you know, the file is still available in the previous commits. Github got an article about removing sensitive data from a repository: https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

Anyway I'll be hanging on and good luck for your exams!

**Comment by monoclecat** [comment]
@rhetenor Thanks for the hint, I think I did it right. I can't find the database in old commits anymore. Corona has me jobless now that my exam has been cancelled, so I'll be furnishing this repo up in the next few days.

**Comment by monoclecat** [comment]
Closing this issue, which doesn't mean this project is anywhere finished yet. See milestone
