### ISSUE TITLE
Restrict access to user email

### ISSUE THREAD

**Issue by rhetenor** [monoclecat/cleaning-schedule-generator#37]
Either from the implemented API and from the user email preferences one can get the email address from the user. Since there are no other security measurements (which I think is okay to keep the system simple to use) this private information should not be accessible at all (without further access restriction it could easily be fished by bots) and If one wants to change the email address he/she can instead contact the admin to do this.

**Comment by monoclecat** [comment]
Thanks for the notice, I finally came around to addressing this issue. I removed any trace of the User model from the API in commit 9dc669470394ade0147ac8460fa9389ffafdf624 .
